#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "yunomonitor"
name = "YunoMonitor"
description.en = "Home made tool to monitor automatically your servers"
description.fr = "Outil pour surveiller automatiquement vos serveurs"

version = "2020.05.15~ynh1"

maintainers = ["ljf"]

[upstream]
license = "AGPL-3.0"
code = "https://github.com/zamentur/yunomonitor"
admindoc = "https://github.com/zamentur/yunomonitor/blob/master/README.md"
fund = "https://donate.yunohost.org/"

[integration]
yunohost = ">= 4.3.0"
architectures = "all"
multi_instance = false
ldap = "not_relevant"
sso = "not_relevant"
disk = "10M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.monitored_servers]
    ask.en = "List all servers you want to monitor with this server (separated by comma)"
    help.en = "You need to install yunomonitor on those servers or add manually a custom configuration file for each server to monitor"
    type = "string"
    example = "example.com,example2.com"
    default = "localhost"

    [install.monitoring_servers]
    ask.en = "List all monitoring servers that monitored this server (separated by comma)"
    type = "string"
    example = "example.com,example2.com"
    optional = true

    [install.mails]
    ask.en = "Mails to which send alerts about servers monitored by this server (separated by comma)"
    type = "string"
    example = "john@example.com,jane@example.com"
    optional = true

    [install.sms_api]
    ask.en = "List here an SMS URL to use to send alerts by SMS (e.g. the internet provider 'free' offers some API for that)"
    type = "string"
    example = "https://smsapi.free-mobile.fr/sendmsg?user=USERID&pass=PASSWORD&msg="
    optional = true

[resources]
    [resources.sources.main]
    url = "https://github.com/zamentur/yunomonitor/archive/9200895dc9bdd634d2866b0721a78665733dfd4c.tar.gz"
    sha256 = "7b89c8c77a24447cf5d57e01dbac486c386bdf617174eec1fcd2a9ad778a6e36"
    autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]

    [resources.apt]
    packages = [
        "python3-dbus",
        "python3-pip",
        "python3-cryptography",
        "python3-paramiko",
        "python3-yaml",
        "python3-dnspython",
        "python3-requests-toolbelt",
        "python3-spf",
        "whois",
        "smartmontools",
    ]
