#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    args.monitored_servers = "remote_domain.tld,remote_domain2.tld"
    args.monitoring_servers = ""
    args.mails = "john@example.com"
    args.sms_api = ""

    test_upgrade_from.64c9fef.name = "Last Packagingv1 version"
