#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

domain=$(yunohost domain list --json | jq -r '.["main"]')
path=/.well-known/yunomonitor/

ynh_app_setting_set --key="domain" --value="$domain"
ynh_app_setting_set --key="path" --value="$path"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod 750 "$install_dir"
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod -R o-rwx "$install_dir"
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R "$app:www-data" "$install_dir"
#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Configuring NGINX web server..."

_yunomonitor_add_nginx_config

#=================================================
# SPECIFIC SETUP
#=================================================
# BUILD YUNOMONITOR
#=================================================
ynh_script_progression "Building Yunomonitor..."

pushd "$install_dir"
    python3 -m pip install pycryptodome pyyaml
popd

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression "Configuring $app's systemd service..."

ynh_config_add_systemd
ynh_config_add --template="systemd.timer" --destination="/etc/systemd/system/$app.timer"

systemctl daemon-reload
systemctl enable "$app.timer" --quiet
systemctl start "$app.timer"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

python3 -c '
import sys
import yaml
split_or_empty = lambda x: [] if x == "" else x.split(",")
print(yaml.dump({
    "mails":                split_or_empty(sys.argv[1]),
    "sms_apis":             split_or_empty(sys.argv[2]),
    "monitored_servers":    split_or_empty(sys.argv[3]),
    "monitoring_servers":   split_or_empty(sys.argv[4]),
}))
' "$mails" "$sms_api" "$monitored_servers" "$monitoring_servers" \
> "$install_dir/conf/$app.yml"

# Calculate and store the config file checksum into the app settings
ynh_store_file_checksum "$install_dir/conf/$app.yml"

#=================================================
# INIT IGNORE FILE
#=================================================

echo "method level server message target" > "$install_dir/conf/ignore_alert.csv"

# Set permissions to app files
chmod u+x "$install_dir/yunomonitor.py"
chmod u+w "$install_dir/conf"
chmod u+w "$install_dir/well-known"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
