#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status "$app" >/dev/null; then
    yunohost service remove "$app"
fi

ynh_systemctl --service="$app" --action="stop" --log_path="systemd" --timeout=15

ynh_safe_rm "/etc/systemd/system/$app.timer"
ynh_config_remove_systemd

_yunomonitor_remove_nginx_config

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
