#!/bin/bash

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE FILES
#=================================================

ynh_script_progression "Restoring app files..."
ynh_restore_everything
#=================================================
# RESTORE USER RIGHTS
#=================================================

# Restore permissions on app files
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod 750 "$install_dir"
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod -R o-rwx "$install_dir"
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R $app:www-data "$install_dir"
chmod u+x "$install_dir/yunomonitor.py"
chmod u+w "$install_dir/conf"
chmod u+w "$install_dir/well-known"

#=================================================
# BUILD YUNOMONITOR
#=================================================
ynh_script_progression "Building Yunomonitor..."

pushd "$install_dir"
    python3 -m pip install pycryptodome
popd

#=================================================
# RESTORE SYSTEMD
#=================================================
ynh_script_progression "Activating systemd timer..."

systemctl daemon-reload
systemctl enable "$app.service" --quiet
systemctl enable "$app.timer" --quiet
systemctl start "$app.timer"

#=================================================
# RELOAD NGINX AND PHP-FPM
#=================================================
ynh_script_progression "Reloading NGINX web server..."

ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
